### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by jalvesaq** [jalvesaq/zotcite#1]
This a continuation of [Nvim-R issue #346](https://github.com/jalvesaq/Nvim-R/issues/346).

Notes:

  - It seems that pandoc doesn't recognize the last `#` as part of the citation key. So, I changed the citation key template to `@zotero_key#citation_key`.

  - I did not `import vim` in `zotero.py` to make it easier to reuse the code with another text editor, such as Gedit or Emacs.

**Comment by jalvesaq** [comment]
@rafaqz I added a note in the README that users will soon be able to use citation.vim to insert citation keys. Did you have time to try converting a markdown document into either PDF or HTML with zotref as a pandoc filter?

**Comment by rafaqz** [comment]
I keep getting this error:

```
"Uni/Masters/Tree_paper/Tree_paper.md" 421L, 21199C
[unite.vim] function zotcite#Init[24]..zotcite#GlobalInit, line 17
[unite.vim] Vim(py3):Traceback (most recent call last):
[unite.vim] Error occurred while executing "open" action!
```
With this config:
```
let $ZCitationTemplate = '{author}{year}{title}'
let $ZoteroSQLpath = '~/Zotero/zotero.sqlite'
let $Zotcite_tmpdir = '~/.cache'
```

One lesson I solidly learned in citation.vim was to transfer very detailed error output from python to vim, or it was impossible to debug the complexity.
That meant wrapping all of the python in a `try` block to make sure those errors get to print in vim:

https://github.com/rafaqz/citation.vim/blob/master/python/citation_vim/citation.py#L20

There might be a better way but I don't know it.

**Comment by jalvesaq** [comment]
With your config I got a lot of error messages displayed by nvim. The reason was missing os.path.exanduser(). This issue should be fixed now.

**Comment by rafaqz** [comment]
Somehow your python is conflicting with Unite.vim. The error dispersal if I disable unite, but not if I just disable citation.vim.

So I can't actually test integration with citation.vim...

**Comment by jalvesaq** [comment]
> The error dispersal if I disable unite, but not if I just disable citation.vim.

So, I think the problem isn't both zotcite and citation.vim trying to access the zotero.sqlite at the same time. I guess it's a conflict at the Python level, and the only solution that I can conceive is not using the `:py*` commands at all, and running the zotcite application as job as I was doing in Nvim-R. I would have just to copy some functions from Nvim-R to zotcite plugin.

**Comment by jalvesaq** [comment]
The citation.vim scheme of putting the zotero key at the end might make it easier to highlight the key, but I guess we don't need four hashtags; one would be enough: `@custom_key#ZOTEROKEY`.

**Comment by rafaqz** [comment]
Thats not the problem I had, it occurs even if I disable citation.vim - its just between zotcite and unite. I'm using vim as well, not nvim. But I'll try to debug a little more and compare it with nvim.

Other points:
- citation.vim also doesn't access the zotero.sqlite, it makes a copy of it and accesses that.
- that citation key format is user defined and not set by citation.vim, you can make it however you like by changing your config.

**Comment by jalvesaq** [comment]
Actually, I forgot my own comment. It's easier to recognize the citation pattern correctly if the zotero key comes first.

**Comment by rafaqz** [comment]
Well citation.vim doesn't determine the format so it can be whatever you like and it will be compatible

**Comment by jalvesaq** [comment]
I tried it now in Vim, and I was able to insert citation keys with both citation.vim and zotcite.

**Comment by rafaqz** [comment]
Ok I worked out what the problem is. Somehow opening a file from unite Fasd (my normal method) there is a bug with zotcite loading:
```
function zotcite#Init[24]..zotcite#GlobalInit, line 17
```

Otherwise its great. The key hiding and highlighting is awesome.

But whenI try to use pandoc I got:
```
Error running filter zotref:
Could not find executable zotref
```

So I put the python3 folder in my PATH. Now I get this:
```
pandoc: paper.md:: openBinaryFile: does not exist (No such file or directory)
```

**Comment by jalvesaq** [comment]
I installed unite-fasd, and put the fasd script in the `~/bin` directory, but when I type anything after doing `:Unite fasd` nothing happens. I also don't see the bug in zotcite#GlobalInit.

Does it work if you do in the terminal emulator

```
pandoc paper.md -s -o paper.html -F /path/to/zotref -F pandoc-citeproc
```
?

**Comment by rafaqz** [comment]
I happens after you load the first .md file with fasd

**Comment by jalvesaq** [comment]
My vacations ended on Sunday, and, unfortunately, I will not have much spare time to look at this issue until the weekend. Anyway, I don't see any error when opening a .md file. The command `:Unite fasd` works, and the command `:Zinfo` indicates that everything is Ok with zotcite, and I'm able to insert citation keys with both zotcite and citation vim.

**Comment by rafaqz** [comment]
Ok no problem. I'll end up working out what the problem is, as I'm pretty
sure I'll be using zotcite whenever I get back to actually writing papers
again instead of code...

**Comment by jalvesaq** [comment]
I still cannot replicate the issue with fasd...

I added a new application: zotbib

**Comment by jalvesaq** [comment]
https://github.com/jalvesaq/zotcite/issues/2#issuecomment-460073398 confirms that it works. So, I'm closing this issue.
