### ISSUE TITLE
error on knitting

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#11]
Hi Jalvesaq

I'm getting a problem when I'm knitting a Rmd

It's throwing this error message.

`[WARNING] Could not parse YAML metadata at line 681 column 1: :51:25: Unexpected '
  '
Traceback (most recent call last):
  File "/home/dano/.local/share/nvim/site/plugged/zotcite/python3/zotref", line 54, in <module>
    j['meta']['references'] = refj['meta']['references']
KeyError: 'references'
Error running filter zotref:
Filter returned error status 1
Error: pandoc document conversion failed with error 83
`

I've pinpointed it to somrthing related to references. If I remove a specific reference in a minimal not working Rmd, it knits, but when I reenter the citation(with the suggested from nvim-r), it fails. If I use <leader>za I get information i nvim about the reference.

I'm missing something, but can not understand what.

Greetings from denmark
Dan Olesen

**Comment by jalvesaq** [comment]
It seems that there is a line break in a reference. The command `:Zrefs' will add the references to the markdown document. Of course, it will be better if the cursor is in the YAML header. Then, you will be able to examine the references and look for something that might be causing the problem.

**Comment by olesendan** [comment]
Hi Jalvesaq.

Thank you, for your time.

I've made an small test, the references is here under. The one which is failing, is with BOLD id. The only difference I see, is attachments, where the one who is failing, have a mix of a stored copy and a linked file.

Would you think, that zotcite looks at where the files for the ciation is?

`references:
  - type: "book"
    id: "NQP27KGC#Mcardle_2010"
    author:
      - family: "McArdle"
        given: "William D"
      - family: "Katch"
        given: "Frank I"
      - family: "Katch"
        given: "Victor L"
    issued:
      - year: "2010"
    publisher: "Lippincott Williams & Wilkins"
    ISBN: "0-7817-9781-0"
    title: "Exercise physiology: nutrition, energy, and human performance"
  - type: "article-journal"
    id: "USWCXYZR#ericsson_1993"
    author:
      - family: "Ericsson"
        given: "K. Anders"
      - family: "Krampe"
        given: "Ralf Th."
      - family: "Tesch-Romer"
        given: "Clemens"
    issued:
      - year: "1993"
    volume: "100"
    issue: "3"
    title: "The Role of Deliberate Practice in the Acquisition of Expert Performance"
    DOI: "10.1037/0033-295X.100.3.363"
    language: "en"
    attachment: "['CPPJSDTC:attachments:ericsson-k/ericsson_1993_the_role_of_deliberate_practice_in_the_acquisition_of_expert_performance.pdf']"
    page: "363-406"
    container-title: "Psychological Review"
    source: "Zotero"
  - type: "book"
    id: "FZ53DH48#Baker_2012"
    author:
      - family: "Baker"
        given: "Joseph"
      - family: "Cobley"
        given: "Steve"
      - family: "Schorer"
        given: "Jörg"
    issued:
      - year: "2012"
    ISBN: "978-0-415-58161-5"
    title: "Talent Identification and Development in Sport : International Perspectives"
    attachment: "['TAVB6XF4:attachments:baker-j/baker_2012_talent_identification_and_development_in_sport_-_international_perspectives.pdf']"
    note: "DOI: 9780415581608"
  - type: "article-journal"
    **id: "8CWGKG2C#Midgley_Mcnaughton_Jones_2007"**
    author:
      - family: "Midgley"
        given: "Adrian W"
      - family: "McNaughton"
        given: "Lars R"
      - family: "Jones"
        given: "Andrew M"
    issued:
      - year: "2007"
    volume: "37"
    issue: "10"
    ISSN: "0112-1642"
    language: "eng"
    title: "Training to enhance the physiological determinants of long-distance running performance"
    DOI: "10.2165/00007256-200737100-00003"
    _attachment: "['EQBSTKA4:attachments:Midgley-et-al-M/midgley-et-al_2007_training_to_enhance_the_physiological_determinants_of_long-distance_running.pdf', 'YW7QBZ97:storage:midgley_et-al_2007_training_to_enhance_the_physiological_determinants_of_long-distance_running.pdf']"_
    URL: "http://www.ncbi.nlm.nih.gov/pubmed/17887811"
    page: "857-880"
    container-title: "Sports medicine (Auckland, N.Z.)"
    note: "PMID: 17887811
arXiv: 1011.1669v3
Place: New Zealand
ISBN: 0112-1642; 0112-1642"
  - type: "article-journal"
    id: "FZCRCNQ3#Abbiss_Laursen_2005"
    author:
      - family: "Abbiss"
        given: "Chris R"
      - family: "Laursen"
        given: "Paul B"
    issued:
      - year: "2005"
    volume: "35"
    issue: "10"
    ISSN: "0112-1642"
    language: "en"
    title: "Models to Explain Fatigue during Prolonged Endurance Cycling:"
    DOI: "10.2165/00007256-200535100-00004"
    _attachment: "['M64FUSFZ:attachments:abbiss-c/abbiss_2005_models_to_explain_fatigue_during_prolonged_endurance_cycling.pdf']"_
    URL: "http://link.springer.com/10.2165/00007256-200535100-00004"
    page: "865-898"
    accessed: "2019-03-26 13:26:08"
    source: "Crossref"
    title-short: "Models to Explain Fatigue during Prolonged Endurance Cycling"
    container-title: "Journal of Sports Medicine"
`

**Comment by jalvesaq** [comment]
I created a markdown document, added the fields above to its YAML header, deleted bold (from the id field) and italic (from the attachment fields) marks and compiled the document with the command:
```
pandoc -F pandoc-citeproc file.md -o file.html -s
```
The HTML file was generated without errors.

**Comment by olesendan** [comment]
Ok.
It's something I'm doing. I notice a difference in your compiling.

I have this in my YAML header
`output:
  pdf_document:
    pandoc_args: ['-F', 'zotref', '-F', 'pandoc-citeproc']`

Does this make a difference?

**Comment by olesendan** [comment]
Hi
I have made the following test.
first I made an test.md with the code underneath. If fails with this command
pandoc -F pandoc-citeproc test.md -o test.pdf -s

But if I remove "note: "PMID: 17887811 from the citation id: "8CWGKG2C#Midgley_Mcnaughton_Jones_2007" 
it works.

when it fails, I get this error: 
[WARNING] Could not parse YAML metadata at line 67 column 1: :41:25: Unexpected '
  '
pandoc-citeproc: reference NQP27KGC#Mcardle_2010 not found
pandoc-citeproc: reference FZCRCNQ3#Abbiss_Laursen_2005 not found
pandoc-citeproc: reference 8CWGKG2C#Midgley_Mcnaughton_Jones_2007 not found

The strange thing is, that I have setup Zotero not to export note.


---
output: 
    pdf_document:
        latex_engine: xelatex
references:
  - type: "book"
    id: "NQP27KGC#Mcardle_2010"
    author:
      - family: "McArdle"
        given: "William D"
      - family: "Katch"
        given: "Frank I"
      - family: "Katch"
        given: "Victor L"
    issued:
      - year: "2010"
    publisher: "Lippincott Williams & Wilkins"
    ISBN: "0-7817-9781-0"
    title: "Exercise physiology: nutrition, energy, and human performance"
  - type: "article-journal"
    id: "8CWGKG2C#Midgley_Mcnaughton_Jones_2007"
    author:
      - family: "Midgley"
        given: "Adrian W"
      - family: "McNaughton"
        given: "Lars R"
      - family: "Jones"
        given: "Andrew M"
    issued:
      - year: "2007"
    volume: "37"
    issue: "10"
    ISSN: "0112-1642"
    language: "eng"
    title: "Training to enhance the physiological determinants of long-distance running performance"
    DOI: "10.2165/00007256-200737100-00003"
    attachment: "['EQBSTKA4:attachments:Midgley-et-al-M/midgley-et-al_2007_training_to_enhance_the_physiological_determinants_of_long-distance_running.pdf', 'YW7QBZ97:storage:midgley_et-al_2007_training_to_enhance_the_physiological_determinants_of_long-distance_running.pdf']"
    URL: "http://www.ncbi.nlm.nih.gov/pubmed/17887811"
    page: "857-880"
    container-title: "Sports medicine (Auckland, N.Z.)"
    note: "PMID: 17887811
    arXiv: 1011.1669v3
    Place: New Zealand
    ISBN: 0112-1642; 0112-1642"
  - type: "article-journal"
    id: "FZCRCNQ3#Abbiss_Laursen_2005"
    author:
      - family: "Abbiss"
        given: "Chris R"
      - family: "Laursen"
        given: "Paul B"
    issued:
      - year: "2005"
    volume: "35"
    issue: "10"
    ISSN: "0112-1642"
    language: "en"
    title: "Models to Explain Fatigue during Prolonged Endurance Cycling:"
    DOI: "10.2165/00007256-200535100-00004"
    attachment: "['M64FUSFZ:attachments:abbiss-c/abbiss_2005_models_to_explain_fatigue_during_prolonged_endurance_cycling.pdf']"
    URL: "http://link.springer.com/10.2165/00007256-200535100-00004"
    page: "865-898"
    accessed: "2019-03-26 13:26:08"
    source: "Crossref"
    title-short: "Models to Explain Fatigue during Prolonged Endurance Cycling"
    container-title: "Journal of Sports Medicine"
---

 
# Teori


[@NQP27KGC#Mcardle_2010] 

 
[@FZCRCNQ3#Abbiss_Laursen_2005].


[@8CWGKG2C#Midgley_Mcnaughton_Jones_2007]
`

`

**Comment by jalvesaq** [comment]
The References includes this:

```yaml
    note: "PMID: 17887811
    arXiv: 1011.1669v3
    Place: New Zealand
    ISBN: 0112-1642; 0112-1642"
```

The quotation marks opens at *note* and closes at *ISBN*.

What actually in the *Extra* field in Zotero? I have to create a bibliographic entry in my Zotero to replicate the issue.

Zotcite reads the Zotero's database directly. It doesn't run Zotero and doesn't consider any of Zotero's configuration.

**Comment by olesendan** [comment]
Ah off course. 
This is exsactly the text string, which is in the Extra field(in the info sidebar) in zotero. This FIeld gets filled with extra information about the reference, when references are imported or merged. This happens quite a lot in my workflow.

/Dan

**Comment by jalvesaq** [comment]
Please, see line 592 of python3/zotero.py. You could try adding "note" to the `dont` list. If it works, I can add a variable to zotcite to allow the customization of the `dont` list.

**Comment by olesendan** [comment]
Hi Jalvesaq.
I will try your advise.
I've never tried to change other peoples code, so I do need a bit of guiding, regarding best practise.

Should I fork your repo, then install the forked repo, or make an branch in your repo, and then change the code there? I've never tried to install another branch than the master?

Greetings
Dan Olesen

**Comment by jalvesaq** [comment]
You could just change the code in the vim-plug repository (if you use vim-plug) and tell me if it fixes the issue. If it works, I will create the variable. Then, you could delete the directory and clone it again.

**Comment by olesendan** [comment]
Hi Jalvesaq.

Thank you, for your advise.

I've changed the code, and done the first test on a minimal doc. It worked. I will try some more testing tonight, will let you know how it vent tomorrow.

/Dan

**Comment by olesendan** [comment]
Hi Jalvesaq.

I've now been running zotcite with "note" in the note list for two weeks. I've not experienced any problems during af bunch of knittings.

Greetings From Denmark
Dan Olesen

**Comment by jalvesaq** [comment]
Thanks for the feedback! I added the environment variable `$Zotcite_exclude` which is documented in the README.
