### ISSUE TITLE
Missing delimiter after search pattern

### ISSUE THREAD

**Issue by acorreya** [jalvesaq/zotcite#15]
I get the below error while opening and md document. Please let know what files would help to debug.

Thank you!

```
Error detected while processing function zotcite#Init[24]..zotcite#GlobalInit:
line   22:
E654: missing delimiter after search pattern:
Error detected while processing function zotcite#Init:
line   24:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by jalvesaq** [comment]
Although I couldn't replicate the issue I did a minor change in the code in hope that it would fix the error for you. Could you update the plugin and try again, please?

**Comment by acorreya** [comment]
@jalvesaq ,

Thank you very much. Works seamlessly now! Took a while to figure out how to work with this tool and incorporate it to the Makefile.

Awesome work!

**Comment by jalvesaq** [comment]
Thanks for your feedback!
