### ISSUE TITLE
Commands Missing from Vim

### ISSUE THREAD

**Issue by TheCedarPrince** [jalvesaq/zotcite#16]
# Hi @jalvesaq,

Great add-on! Thank you! I am currently having an issue where I installed your extension via Plug but am having issues with having the add-on work.

Currently, I only have `:Zinfo` and `:Zodt2md` available to me as functions. Nothing else is showing up. Furthermore, I do not receive any omni-completion when I try to execute `<C-x><C-o>` over a key that I am trying to reference from my bib file.

What am I doing incorrectly? Do I need to configure something first that I missed? I believe I have everything set-up properly so I am quite confused.

Thanks for the help!

# Additional Info:

## Vim Info:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 17 2020 05:10:37)
Included patches: 1-587
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
```

## OS Info:

```
          /:-------------:\          cedarprince@obsidian 
       :-------------------::        -------------------- 
     :-----------/shhOHbmp---:\      OS: Fedora x86_64 
   /-----------omMMMNNNMMD  ---:     Host: XPS 15 7590 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.6.13-100.fc30.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 3 hours, 54 mins 
,------------:MMMd--------    ---:   Shell: zsh 
:------------:MMMd-------    .---:   Resolution: 1920x1080 
:----    oNMMMMMMMMMNho     .----:   DE: Plasma 
:--     .+shhhMMMmhhy++   .------/   WM Theme: Sweet-Dark-transparent 
:-    -------:MMMd--------------:    CPU: Intel i7-9750H (12) @ 4.500GHz 
:-   --------/MMMd-------------;     Memory: 2982MiB / 15639MiB 
:-    ------/hMMMy------------:
:-- :dMNdhhdNMMNo------------;
:---:sdNMMMMNds:------------:
:------:://:-------------::
:---------------------://
```

**Comment by jalvesaq** [comment]
What is the output of `:Zinfo`?

**Comment by TheCedarPrince** [comment]
`:Zinfo` output:

```
Information from the Python module:
  zotero.sqlite     : /home/cedarprince/Zotero/zotero.sqlite
  tmpdir            : /home/cedarprince/.cache/zotcite
  data dir          : /home/cedarprince/Zotero
  zotero.py         : /home/cedarprince/.vim/addons/zotcite/python3/zotero.py
  attachments dir   :
  references found  : 572
  excluded fields   : []
  citation template : {Authors}_{Year}
  docs              : {'/home/src/Offline/Zettelkasten/03292020180520-smart-notes.md': []}
  banned words      : a an the some from on in to of do with

Additional messages:
There is another omnifunc enabled: htmlcomplete#CompleteTags
Not enabled for "05162020023355-article-1.md" (bibliography: zettel.bib)
Not enabled for "03302020005409-note-criteria.md" (bibliography: zettel.bib)
Not enabled for "05032020155207-fabrication-serendipity.md" (bibliography: zettel.bib)
```

Also, now, after doing nothing that I can recall, I have the functions available to me. However, upon omnicompletion, I do not have anything propagate other than this error:

`Pattern not found`

Do you know why this still may be failing for inserting a key?

**Comment by TheCedarPrince** [comment]
P.S. Furthermore, I do not understand the `Not enabled for` statement. What does it mean?

**Comment by jalvesaq** [comment]
Your output says: "There is another omnifunc enabled: htmlcomplete#CompleteTags".
Can you disable the plugin that provides `htmlcomplete#CompleteTags`?
You also have to remove from the YAML header of each markdown document the `bibliography` entry.

**Comment by TheCedarPrince** [comment]
Hey @jalvesaq ,

I tried to figure out where that function is defined in my `.vimrc` plugins. However, even after disabling everything in my `.vimrc` the omnifunc issue persisted. Do you have any suggestions about what to do about this?

Also, the bibliography entry is removed from the article I am trying to get this zotero to see. Thoughts?

**Comment by jalvesaq** [comment]
Could you update the plugin and try again, please?

**Comment by TheCedarPrince** [comment]
Hey @jalvesaq,

I can confirm that this works now! Whatever you updated seems to work now. Thanks for the help!

**Comment by jalvesaq** [comment]
Zotcite's omni completion will work only if the keyword being completed starts with '@'. Otherwise, it will call the 'omnifunc' defined before zotcite was loaded, in your case, `htmlcomplete#CompleteTags`. This means that `<tab` should complete to `<table` and `@bio` should complete a reference with the string "bio" in either the titles or authors' names.
