### ISSUE TITLE
zotcite Hides markdown headers

### ISSUE THREAD

**Issue by naught101** [jalvesaq/zotcite#18]
If I write markdown headers with leading hashes, which is my preferred method, zotcite hides the hashes (all of them, regardless of number). This is annoying, because it means that my syntax highlighting no longer works, and I can't see where my headers are until I move the cursor over them.

The concealing is kind of nice for the actual references, but it seems like the matching is a bit overzealous. Would it be possible to change the hiding so it only hides the parts between the @ and # (including the #), so that something like
```
@UHZLCJQR#Kjellstrom_Maître_2019
```
becomes
```
@Kjellstrom_Maître_2019
```
?

**Comment by jalvesaq** [comment]
I also use leading hashes for headers, and zotcite doesn't hide them:

![image](https://user-images.githubusercontent.com/891655/89030599-2cea3600-d307-11ea-8bd3-39f757a7ffea.png)

Maybe another plugin is hiding them.

I prefer to hide both the `@` and `#` symbols in citation keys to make the displayed text closer to the output that will be generated (either PDF or HTML) which is the purpose of the concealing feature, but I can add an option to not hide the `@` symbol.

**Comment by naught101** [comment]
The headers were never hidden before I installed zotcite, and if I set `let zotcite_hl=0` in my `.vimrc`, the problem disappears, so it is definitely zotcite related. But yes, it may be related to another plugin. These are the plugins I have installed:

```
$ls ~/.vim/bundle 
ale                     Nvim-R        vim-commentary     vim-indent-object       vim-speeddating  VOoM
coverage-highlight.vim  tagbar        vim-desertink      vim-jsx-improve         vim-surround     YouCompleteMe
csv.vim                 todo.txt-vim  vim-dirdiff        vim-pandoc-syntax       vim-table-mode   zotcite
matchit                 UltiSnips     vim-fugitive       vim-python-pep8-indent  vim-titlecase
molokai                 vim-airline   vim-indent-guides  vim-snippets            vim-vinegar
```

If there's anything else I can check (is there a way to display hiding rules somehow?), let me know.

**Comment by jalvesaq** [comment]
I can replicate the issue now. The problem is that my attempt of integrating zotcite syntax highlighting with vim-pandoc-syntax no longer works. I'm sorry, but I give up trying to integrating them. So, please, put in your vimrc:

```vim
let zotcite_hl = 0
```

**Comment by jalvesaq** [comment]
You no longer need `zotcite_hl = 0` in your vimrc because I deleted the attempt of replacing pandoc syntax. If someone wants to write the code for pandoc syntax, I will accept the pull request.
