### ISSUE TITLE
failed to create ZoteroEntries object

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#2]
Hi.

I'm trying to learn who to use your plugin.

I've switched from win to linux, and is trying to learn a new workflow in vim with zotero and zotcite.

I've installed zotcite with Vundle.

When I open vim, I'm getting the following erorrs. I've probelly done something wrong.
I've set the path to zotero as an absolute path
'/home/dano/Documents/zotero/zotero.sqlite'

This is the errors i'm getting:
Error detected while processing function zotcite#Init[24]..zotcite#GlobalInit:
line   17:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dano/.vim/bundle/zotcite/python3/zotero.py", line 250, in __init__
    self._load_zotero_data()
  File "/home/dano/.vim/bundle/zotcite/python3/zotero.py", line 296, in _load_zotero_data
    self._add_attachments()
  File "/home/dano/.vim/bundle/zotcite/python3/zotero.py", line 410, in _add_attachments
    self._e[pId]['attachment'] = pKey + ':' + aPath
KeyError: None
Failed to create ZoteroEntries object.

Greetings from Denmark
Dan Olesen

**Comment by jalvesaq** [comment]
I started using Zotero not a long ago, and my Zotero database is still simple. So, I have not seen this bug yet, but I believe it's fixed now. Could you update the plugin and try again?

**Comment by jalvesaq** [comment]
You are not missing any mappings. Ctrl-X Ctrl-O should work.

For example, if there is a reference like this in your Zotero database:

Marx, Karl & Engels, Friedrich. (1848) *The communist manifesto*.

Then, omnicompletion should work with any of the following (the vertical bar represents the cursor position):

```
@marx|
@eng|
@manif|
```
And you should get something like `@WS94MDUK#Marx_1848`, where `WS94MDUK` would be the key used internally by Zotero.

**Comment by jalvesaq** [comment]
I have never tested with a Zotero plugin that allows you to set custom keys (I don't remember its name).

**Comment by olesendan** [comment]
When I enter :Zinfo I get this.

Information from the Python module:
  zotero.sqlite     : /home/dano/Documents/zotero/zotero.sqlite
  tmpdir            : /home/dano/.vim/cache/
  references found  : 47
  zotero.py         : /home/dano/.vim/bundle/zotcite/python3/zotero.py
  citation template : {Author}_{Year}
  docs              : {'/home/dano/projects/temp/test.md': []}
  banned words      : a an the some from on in to of do with

Additional messages:
There is another omnifunc enabled: pandoc#completion#Complete

**Comment by jalvesaq** [comment]
Quoting zotcite's README:

> Note that Zotcite will not enable omni completion if any of the buffer's lines matches the regular pattern `^bibliography:.*\.bib` when the markdown file is read.

So, if you have a `bibliography` field in the YAML header of the markdown document, please, delete it.
The last time I tested it, `pandoc#completion#Complete` only did bib completion which is no longer necessary if using zotcite. So, if deleting the `bibliography` field is not enough, you will have to disable pandoc completion in order to be able to use zotcite completion.

**Comment by olesendan** [comment]
Hi Agian.

So now I think, I have disabled pandoc completion.
The behaviour is the same. I'm still getting the 
"Omni completion (^O^N^P) Pattern not found."

But from Zinfo it does not say, that pandoc completion is set. print from Zinfo:
Information from the Python module:
  zotero.sqlite     : /home/dano/Documents/zotero/zotero.sqlite
  tmpdir            : /home/dano/.vim/cache/
  references found  : 47
  zotero.py         : /home/dano/.vim/bundle/zotcite/python3/zotero.py
  citation template : {Author}_{Year}
  docs              : {'/home/dano/projects/temp/test.md': []}
  banned words      : a an the some from on in to of do with

**Comment by jalvesaq** [comment]
> Do I now, set omnifouc in zotcite?

You shouldn't do anything. Zotcite is a general plugin that enables its functions only if the file type is `markdown`, `pandoc` or `rmd`. If I start editing an empty `test.md`, the completion already works. I'm using neovim and vim-plug, and I just tried it with the following `~/config/nvim/init.vim` (three lines only):

```
call plug#begin('~/.cache/vim-plug')
Plug 'jalvesaq/zotcite'
call plug#end()
```

**Comment by olesendan** [comment]
Hi Jalvesaq.

I'm using Vim and Vundle. It seems, that your plugin is installed.
Can I check if If have set VIm to support Python 3?. I've installed python, but I'm unsure, if support is enabled in Vim.
I'll see if I can figure out how to check Vim
Greetings
Dan Olesen

**Comment by olesendan** [comment]
Hi Javlesaq

You are right, if I make a minimal vimrc, only iwth Vundel and zotcite, it works.
So can you give an advise to a newbie. What steps should I do now. Add one plugin at a time?

Greetings 
Dan Olesen

**Comment by jalvesaq** [comment]
@olesendan did you find what was making zotcite fail?

**Comment by jalvesaq** [comment]
Since the ZoteroEntries object is being created, I'm closing this issue. Please, open another issue if you find what plugin or Vim configuration is incompatible with zotcite.

**Comment by olesendan** [comment]
Hi Jalvesaq.

I can confirm, that your plugin works with a minimal vimrc.

After some thinking, I've decieded to use citation.vim. The reason for that, is the format which citations have, when they are inserted in the doc. I would like to render some to markdown, so I believe, that the format from citation.vim ([@xxxxxx]) renders better in markdown. But I've not have time to run som echecks yet.

Thanks for your help!
Greetings from denmark
Dan Olesen

**Comment by jalvesaq** [comment]
Thanks for the feedback!
