### ISSUE TITLE
cannot find MarkDown file to convert

### ISSUE THREAD

**Issue by whytong** [jalvesaq/zotcite#22]
Thanks for this interesting vim package. I'm trying it out and found some issues with pandoc conversion. When I type 
```:!pandoc test.md -s -o test.pdf -F zotref -F pandoc-citeproc ``` when editing the ```test.md``` file, it returns ```pandoc: test.md: openBinaryFile: does not exist (No such file or directory)```. If I indicate the fullpath of the ```test.md``` file, then it produces the ```test.pdf``` file under the home directory. I am wondering whether there is a way to omit the full path of the file.

**Comment by jalvesaq** [comment]
This issue might be related to the Vim option `autochdir`. What is the output of `:!pwd`?

**Comment by whytong** [comment]
Sorry, I fiddled around and could not reproduce the error now. The pandoc conversion line is now working under WSL2, and generated output properly. Maybe I did not reopen the session. Thank you.
