### ISSUE TITLE
zotref not found (Cygwin/Windows 10)

### ISSUE THREAD

**Issue by whytong** [jalvesaq/zotcite#23]
Hi Jakson,

Thanks for the great plugin. It works excellent in Ubuntu on WSL2. However, when I tried to make it work on Cygwin/Windows 10, I run into trouble of invoking ``zotref``.

I used the same configuration as that on WSL2, the file ``/cygdrive/c/Users/whyt/.vim/plugged/zotcite/python3/zotref`` exists and is executable but when I run ``:!pandoc test.md -s -o test.pdf -F zotref -F pandoc-citeproc`` in vim it gives the following error message.

```
Error running filter /cygdrive/c/Users/whyt/.vim/plugged/zotcite/python3/zotref:
Could not find executable /cygdrive/c/Users/whyt/.vim/plugged/zotcite/python3/zotref

shell returned 83

Press ENTER or type command to continue
```

Vim: 8.2.486
Modified by cygwin.

**Comment by jalvesaq** [comment]
I'm sorry, but I can't help because I don't use Cygwin.

**Comment by jalvesaq** [comment]
I added the "py" extension to Python scripts a month ago (https://github.com/jalvesaq/zotcite/commit/8414b96e006b708a67a087bbefe5fb0da88f5c78). Did this change make any difference?

**Comment by whytong** [comment]
Thanks for the update. No, no luck finding `zotref`. I was using Cygwin b/c Winter Terminal does not have bold font, but MobXterm makes it easy to use Linux terminals, so I switched it over.

**Comment by whytong** [comment]
Actually, the error messages are different, pre-update, it says the `zotref` cannot be found, after the update, it says: 
> Error running filter zotref.py:
> zotref.py: createProcess: invalid argument (Exec format error)

**Comment by jalvesaq** [comment]
I'm sorry, but it worked the last time that I tried it on Windows running in a virtual machine, and I can't fix an issue that I can't replicate unless I had good knowledge of Windows environment, which I don't.

**Comment by whytong** [comment]
No worries. I guess you shall close it.

**Comment by jalvesaq** [comment]
We may let the issue open in the hope that someone who knows how to fix the issue will comment here...

**Comment by jalvesaq** [comment]
Nobody fixed the issue after three years, so I'm closing it now.
