### ISSUE TITLE
Broken citation key part after # when the name contains a prime symbol '

### ISSUE THREAD

**Issue by whytong** [jalvesaq/zotcite#24]
System: Vim 8.2 on Ubuntu/WSL2

Issue:
When the first author of the citation contains a prime symbol, say ``O'Leary``, the citation key is not properly recognized. In this case, the markdown file still shows ``@9RDI3FXC#O'Leary_2014``, but the ``Zrefs`` output does not include the **'Leary_2014** part, and when it passes through ``pandoc``, the output does generate, but  **'Leary_2014** becomes extra text, i.e. it shows ``O'Leary (2014)'Leary_2014``

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. It's was fixed in the last commit.
