### ISSUE TITLE
compatibility with vimwiki

### ISSUE THREAD

**Issue by LortKrassbeter** [jalvesaq/zotcite#27]
Hi,

since vim-wiki has a markdown mode I was wondering how zotcite could be made compatible with it. 
When testing with both plugins installed vim-wiki wins out on claiming markdown files and hence zotfiles functions and the `omnifunc` functionality do not work.
On the other hand zotcite still works as intended in R markdown.

I don't know much about vimscript, so I just commented out vim-wiki's `setlocal omnifunc=Complete_wikifiles` to see if I could use zotcite's instead, but this just causes an empty `omnifunc=`.

Is there a fix to enable both plugins to work with markdown files simultaneously (and just use one of the two `omnifunc`)?

Cheers

**Comment by jalvesaq** [comment]
I forgot to document the option `zotcite_filetypes`. I'm sorry about that.
Does it work if you put in your vimrc or init.vim:

```
let zotcite_filetypes = ['markdown', 'pandoc', 'rmd', 'vimwiki']
```

**Comment by LortKrassbeter** [comment]
Yes, this makes it work when I disable vimwikis completion. Thanks!

**Comment by jalvesaq** [comment]
You should not have to disable vimwiki completion because zotcite should call it if the pattern being completed doesn't begin with `@`.

You could also try to enable syntax highlighting of zotcite's reference keys with the command below (of course, you have to write the correct path to `markdown.vim`):

```
autocmd FileType vimwiki source /path/to/zotcite/after/syntax/markdown.vim
```
