### ISSUE TITLE
Cannot select from multiple matched references

### ISSUE THREAD

**Issue by whytong** [jalvesaq/zotcite#28]
Happy New Year, Jakson and thank you again for the great plugin.

I have this issue of unable to select from multiple matches and not sure what went wrong. Attached is a screen shot of the issue. After I type `Ctrl-X` and `Ctrl-O`, it does give me two matching refs, however, when I move the up/down arrows, the status bar at the bottom changes but not the citekey. So I always end up with the first matched ref if I hit `Enter`.

![20210107_164755](https://user-images.githubusercontent.com/54590532/103949481-52c30480-5109-11eb-9c26-2cff4707361e.gif)

System tested not working for 
Vim 8.2.1897 (jonathon.fernyhough modification) on 
Ubuntu 20.04 on WSL2

Works sometimes for NeoVim 0.4.4 (Snap built) or Vim 8.2.1897 (jonathon.fernyhough modification) on Linux Mint 19.3.
Sometimes it does not find a match for certain search words (e.g. name of the author who's not the first), and sometimes it finds one match (when there are two matches).

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue. The omnicompletion works fine with Vim 8.2.716, Neovim 0.4.4, and the development version of Neovim, all on Ubuntu 20.10.

Does omnicompletion in other file types (not related to zotcite) work?

**Comment by whytong** [comment]
Yes. The `omnifunc` works find for HTML (=htmlcomplete#CompleteTags), but not in this case omnifunc=ZotCite#CompleteBib. I am using the same configuration by openning one HTML file and one MD file in the same vim session. The weird part is that I see the matched item changes (in the statusline) when I move the cursor but the matched item is not inserted. Is there anything else I shall look into?

**Comment by jalvesaq** [comment]
With [cmp-zotcite](https://github.com/jalvesaq/cmp-zotcite) more entries are found, thanks to [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) fuzzy matching algorithm.
