### ISSUE TITLE
failed to create ZoteroEntries object again

### ISSUE THREAD

**Issue by xiaoouwang** [jalvesaq/zotcite#3]
I've checked the previous issue but it seems that the problem appeared again on neovim. Here is the message:

Greetings

![image](https://user-images.githubusercontent.com/16024291/54644281-4b94b780-4a99-11e9-9abc-38ac5f84d601.png)

**Comment by jalvesaq** [comment]
Maybe Zotero database stores information on attachments whose parent item was deleted. So, I added `not pKey is None` to the condition preceding the line with the error. 
Does it work now?

**Comment by xiaoouwang** [comment]
@jalvesaq hum I updated the plugin but the same error persists...

**Comment by xiaoouwang** [comment]
> Maybe Zotero database stores information on attachments whose parent item was deleted. So, I added `not pKey is None` to the condition preceding the line with the error.
> Does it work now?
It works now ! However when I press ctrl x ctrl o the following error comes

![image](https://user-images.githubusercontent.com/16024291/54673211-19677200-4afa-11e9-9282-8904887a898e.png)

**Comment by xiaoouwang** [comment]
the Zinfo tells me that another omnifunc is enabled called CompleteR I don't know if it interferes with the plugin.

**Comment by jalvesaq** [comment]
> the Zinfo tells me that another omnifunc is enabled called CompleteR I don't know if it interferes with the plugin.

This is not a problem because `CompleteR` is from Nvim-R and it calls `RmdNonRCompletion` when the cursor is not in R code and, finally, `RmdNonRCompletion` calls `zotcite#CompleteBib` if it exists.

The real problem is that the Python object `ZotCite` is not defined. Although you are no longer getting the message "failed to create ZoteroEntries object", the object was not created. The output of `:Zinfo` in an Rmd file should be like this:

```
Information from the Python module:
  zotero.sqlite     : /home/yourlogin/Zotero/zotero.sqlite
  tmpdir            : /home/yourlogin/.cache/zotcite
  references found  : 157
  zotero.py         : /home/yourlogin/.config/nvim/plugged/zotcite/python3/zotero.py
  citation template : {Authors}_{Year}
  docs              : {'/tmp/test.Rmd': []}
  banned words      : a an the some from on in to of do with

Additional messages:
There is another omnifunc enabled: CompleteR
```

**Comment by xiaoouwang** [comment]
> > the Zinfo tells me that another omnifunc is enabled called CompleteR I don't know if it interferes with the plugin.
> 
> This is not a problem because `CompleteR` is from Nvim-R and it calls `RmdNonRCompletion` when the cursor is not in R code and, finally, `RmdNonRCompletion` calls `zotcite#CompleteBib` if it exists.
> 
> The real problem is that the Python object `ZotCite` is not defined. Although you are no longer getting the message "failed to create ZoteroEntries object", the object was not created. The output of `:Zinfo` in an Rmd file should be like this:
> 
> ```
> Information from the Python module:
>   zotero.sqlite     : /home/yourlogin/Zotero/zotero.sqlite
>   tmpdir            : /home/yourlogin/.cache/zotcite
>   references found  : 157
>   zotero.py         : /home/yourlogin/.config/nvim/plugged/zotcite/python3/zotero.py
>   citation template : {Authors}_{Year}
>   docs              : {'/tmp/test.Rmd': []}
>   banned words      : a an the some from on in to of do with
> 
> Additional messages:
> There is another omnifunc enabled: CompleteR
> ```

Yes and when I open a new markdown with only zotcite enabled it failed to build the python object too. The plugin citation.vim works.

**Comment by jalvesaq** [comment]
I started using Zotero a few months ago. My zotero.sqlite database is quite new and I don't have any error here. If you issue the command `:messages`, do you see any error messages preceeding the "failed to create ZoteroEntries object"?

**Comment by jalvesaq** [comment]
@xiaoouwang I believe that the bug that you reported (zotero.py, line 400) is fixed. Please, could you update the plugin and try again?

**Comment by jalvesaq** [comment]
I'm closing the issue because I believe it is fixed. Please, open it again if you still see the problem.
