### ISSUE TITLE
Installed required modules but received errors

### ISSUE THREAD

**Issue by duytientran** [jalvesaq/zotcite#34]
Hi, I have installed all packages required, however it seems my Manjaro system does not "know" where to look for packages it needs. I used neovim 0.5 for this if that helps. Would you please tell me how can I fix this ? Thanks 
Traceback (most recent call last):
  File "/home/arenberg/.config/nvim/plugged/zotcite/python3/pdfnotes.py", line 12, in <module>
    import popplerqt5
ModuleNotFoundError: No module named 'popplerqt5'

**Comment by jalvesaq** [comment]
The module `popplerqt5` is required only to import notes from PDF documents. If this is the only problem, most of zotcite should be functional.

I use `pip3` to install Python modules. Be sure to install Python 3 (not Python 2) modules.
