### ISSUE TITLE
Conflicts with vim-markdown

### ISSUE THREAD

**Issue by mara-kr** [jalvesaq/zotcite#36]
Hi! There's some plugin interference that I'd love some help debugging -- completion works fine, highlighting works without vim-markdown, but breaks with vim-markdown installed. I'm happy to help debug, but I'm not entirely sure where to start.

This is a phenomenal plugin; I'm just bugged by seeing all the citation keys marked as misspelled words.

**Comment by jalvesaq** [comment]
I can merge a pull request fixing the issue if someone writes one. However, note that the last issue closed in vim-markdown was in June 2020, and since then more than 30 new issues were open. The last commit was in July 2020. So, it seems that vim-markdown isn't being actively maintained.
