### ISSUE TITLE
Attached pdf can not find

### ISSUE THREAD

**Issue by lsli0116** [jalvesaq/zotcite#37]
I am using macOS Monterey and use the zotcite with vim. And other function works well except for the <C-]> for opening the attached pdf. It will tell me that the following message:

> Could not find "~/Documents/zotero/storage/845NSI86/Wu_et_al-2012-Precambrian_Research-Geochemistry_and_zircon_U–Pb_geochronology_of_Paleoproterozoic_arc_related.pdf"

But when I copy this path in my shell, the path exists and points to the pdf file. It is really strange, and I don't know how to fix it.

**Comment by jalvesaq** [comment]
It seems to be a problem of path expansion: `~` isn't being expanded to your home directory.

**Comment by jalvesaq** [comment]
What's the output of

```
:echo g:zotcite_attach_dir
```
?

**Comment by lsli0116** [comment]
> 

There is no output of `echo g:zotcite_attach_dir`, but after I manually expand the `~` in my vimrc, it works. Thanks for your answers! @jalvesaq
