### ISSUE TITLE
Error: typeerror: must be str. not NoneType

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#4]
Hi All.

I've tried to set up your plugin again. I really want it to work. I've moved to neovim, an I'm getting this output from :messages 

Error detected while processing /home/dano/.config/nvim/spell/en.utf-8.add.spl:
E757: This does not look like a spell file
NERDTree: CWD is now: /home/dano
NERDTree: 1 file(s) could not be loaded into the NERD tree
Error detected while processing function zotcite#Init[24]..zotcite#GlobalInit[17]..provider#python3#Call:
line   18:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 250, in __init__self._load_zotero_data()
File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 297, in _load_zotero_data
self._add_attachments()
File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 400, in
_add_attachments
self._e[pId]['attachment'] = pKey + ':' + aPath
TypeError: must be str, not NoneType
Failed to create ZoteroEntries object.  

It seems, that there is an error when when the plugin tries to attach data from Zotero.

Is there anything I can do. I'm loading the following plugins. I'm wundering, if the order of plugins is important?

Plugin 'VundleVim/Vundle.vim'
Plugin 'sjl/badwolf'
Plugin 'itchyny/lightline.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'scrooloose/nerdtree'
Plugin 'Soares/butane.vim'
Plugin 'mrk21/yaml-vim'
Plugin 'ferrine/md-img-paste.vim'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'tomtom/tcomment_vim'
Plugin 'w0rp/ale'
Plugin 'chrisbra/csv.vim'
Plugin 'jalvesaq/Nvim-R'
Plugin 'rizzatti/dash.vim'
Plugin 'ncm2/ncm2'
Plugin 'roxma/nvim-yarp'
Plugin 'gaalcaras/ncm-R'
Plugin 'ncm2/ncm2-bufword'
Plugin 'ncm2/ncm2-path'
Plugin 'jalvesaq/zotcite'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'vim-pandoc/vim-rmarkdown'
Plugin 'JamshedVesuna/vim-markdown-preview'
Plugin 'vim-pandoc/vim-markdownfootnotes' 

Greetings from Denmark

**Comment by jalvesaq** [comment]
Could you please update the plugin and try again?

**Comment by olesendan** [comment]
Hi Jalvesaq

after the update, I get a new error, see below. I dont understand the statement lastname. In my init.vim I have defined 

let $ZCitationTemplate = '{Author}_{Year}'  



Error detected while processing function zotcite#Init[24]..zotcite#GlobalInit[17]..provider#python3#Call:
                                                                                                         
line   18:                                                                                               
Traceback (most recent call last):                                                                       
  File "<string>", line 1, in <module>                                                                   
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 250, in __init__                 
    self._load_zotero_data()                                                                             
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 298, in _load_zotero_data        
    self._calculate_citekeys()                                                                           
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 431, in _calculate_citekeys      
    key = re.sub('{authors}', lastnames.lower(), key)                                                    
UnboundLocalError: local variable 'lastnames' referenced before assignment                               
Failed to create ZoteroEntries object.

**Comment by olesendan** [comment]
Hi Jalvesaq

after the update, I get a new error, see below. I dont understand the statement lastname. In my init.vim I have defined 

let $ZCitationTemplate = '{Author}_{Year}'  



Error detected while processing function zotcite#Init[24]..zotcite#GlobalInit[17]..provider#python3#Call:
                                                                                                         
line   18:                                                                                               
Traceback (most recent call last):                                                                       
  File "<string>", line 1, in <module>                                                                   
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 250, in __init__                 
    self._load_zotero_data()                                                                             
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 298, in _load_zotero_data        
    self._calculate_citekeys()                                                                           
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 431, in _calculate_citekeys      
    key = re.sub('{authors}', lastnames.lower(), key)                                                    
UnboundLocalError: local variable 'lastnames' referenced before assignment                               
Failed to create ZoteroEntries object.

**Comment by jalvesaq** [comment]
The `lastnames` bug should be fixed now. Could you try again?

**Comment by olesendan** [comment]
Hi Jalvesaq.

I do not get the error now.

:Zinfo outputs this.

Information from the Python module:                                                                                                                                                                                
  zotero.sqlite     : /home/dano/Documents/zotero/zotero.sqlite                                                                                                                                                    
  tmpdir            : /home/dano/.config/nvim/cache/                                                                                                                                                               
  references found  : 3922                                                                                                                                                                                         
  zotero.py         : /home/dano/.config/nvim/bundle/zotcite/python3/zotero.py                                                                                                                                     
  citation template : {Author}_{Year}                                                                                                                                                                              
  docs              : {'/home/dano/projects/cant-scient/speciale/opgave-speciale/paper/20_metode.Rmd': []}                                                                                                         
  banned words      : a an the some from on in to of do with                                                                                                                                                       
                                                                                                                                                                                                                   
Additional messages:                                                                                                                                                                                               
There is another omnifunc enabled: CompleteR   

What do the last line mean? I understand that nvim-r uses omnifunc, but does it result in conflicts?

When I try to inset citations via crtl-x crtl-o it does not work. Do I need to alter mappings?

Greetings from Denmark
Dan

**Comment by jalvesaq** [comment]
> There is another omnifunc enabled: CompleteR

This is fine because `CompleteR` calls the function pointed by `b:rplugin_r_plugin_nonr_omnifunc` when the cursor is not within an R chunk. And this function should be `RmdNonRCompletion` which calls `zotcite#CompleteBib` (unless there is a bib file in the same directory of the Rmd script).
