### ISSUE TITLE
How to add some extra words when I cite

### ISSUE THREAD

**Issue by lsli0116** [jalvesaq/zotcite#42]
Hi there,

The `zotcite` is a very nice plugin for me to write papers in markdown. But I meet some problems when I want to add some extra words in citations. For examples,` [@3KXK5A56#wang2014 and references therein] `can cite one paper and add "and reference therein" in the parenthesis, when I use pandoc to translate the md file to docx file. 
<img width="359" alt="截屏2022-04-16 16 25 30" src="https://user-images.githubusercontent.com/34978045/163668059-23e4ec59-b935-4480-8bd2-2030e531a76c.png">
But when I add two or more papers, such as  `[@7GF3T4MT#zhao2012; @3P7QGGYM#zhao2015 and references therein]` the output will be like this:
<img width="531" alt="截屏2022-04-16 16 26 08" src="https://user-images.githubusercontent.com/34978045/163668082-e90b0922-2796-45f4-bd78-4e666c2465bc.png">
The order will change automatically, and I cannot manage it to ensure the extra text in the last in the paranthesis.

Thanks in advance!

**Comment by jalvesaq** [comment]
Are you sure that the same csl style is used in both cases? Please, see: https://docs.citationstyles.org/en/stable/specification.html#sorting
