### ISSUE TITLE
Omni citation won't search in title words 

### ISSUE THREAD

**Issue by marcozer** [jalvesaq/zotcite#44]
Hi, 

I am first of all very glad to use your plugin.
I cannot add any citations while searching for words in my article titles. While it does work well if I search for author names. 

Here is my Zinfo output : 
![zinfo](https://user-images.githubusercontent.com/50965141/167252169-b9265f54-9e89-424c-9b22-6d9b94d9446e.png)
Thank you for your help

**Comment by jalvesaq** [comment]
I can't replicate the issue with `<c-x><c-o>`, but I noted that the list of items is incomplete if using `nvim-cmp`, a plugin for automatic omni completion. Anyway, articles matching author names will appear before articles matching only titles.

**Comment by jalvesaq** [comment]
If you were using `cmp-omni`, the issue can now be fixed if you use [cmp-zotcite](https://github.com/jalvesaq/cmp-zotcite) instead.
