### ISSUE TITLE
Zotero's 'Extra' field is not recognized when using publication date ranges in `zotcite`.

### ISSUE THREAD

**Issue by argosatcore** [jalvesaq/zotcite#45]
Hi,

First, I would like to thank you for writing such an amazing and useful program. I use it practically every day, and I am very satisfied with it.

Recently, I cited a journal article that has a publication range date, but Zotero's date field curretly doesn't support date ranges. However, according to this [post](https://forums.zotero.org/discussion/84820/month-range-in-date-field-rendered-incorrectly), specifically to adamsmith's response, one can circunvent this issue by adding the following info in Zoter's extra field, under the source's info tab:

>The date field currently isn't able to understand date ranges in any format. 
>If you really want the range, entering the date as 
>`issued: 2013-07/2013-08` in the Extra field will work 

After adding the publication date range as per adamsmith's suggestion, Zotero's citation plug-in in  LibreOffice Writer was able to pull up the date range, but when I used `zotcite`, the citation is displayed without a date. When I use `<Leader>za` to display the citation's information, the 'Extra' field is shown with the date range information, so it is recognized by `zotcite`, but it is not incorporated when converting the citation key into a complete citation in pdf format.

Do you think it would be possible to add support for date ranges in `zotcite` by using Zotero's extra field?

In case this is useful, I am using Debian Sid, `pandoc`'s version is 2.9.2.1, and `neovim`'s version is 0.6.1.

Best regards,

Argos

**Comment by jalvesaq** [comment]
I tried Adam Smith's suggestion but it didn't work for me on LibreOffice. Anyway, the "Extra" field is added to the YAML header as "note", as you can see with the command `:Zrefs`. As far as I know, it's the citation style that defines whether the "note" field is used or not.

I can't add support to date ranges because the references are processed by Pandoc, and not by Zotcite. What I can do is to change the translation of "extra" into "note" if "note" is the wrong translation.

**Comment by argosatcore** [comment]
>As far as I know, it's the citation style that defines whether the "note" field is used or not.

I see. I use the Chicago Manual of Style, 17th edition (full note). Maybe that has something to do with Adam Smith's suggestion not working for you?

>I can't add support to date ranges because the references are processed by Pandoc, and not by Zotcite. What I can do is to change the translation of "extra" into "note" if "note" is the wrong translation.

Ah, I see. Yes, I think changing "note" to "extra" would be better.

Thanks for your response!
