### ISSUE TITLE
Feature Request: Support Multiple Keywords

### ISSUE THREAD

**Issue by acorreya** [jalvesaq/zotcite#46]
I am writing a literature review, and there are too many references for me to lookup with a single keyword, and sometimes even when using author name. It would be great if there was a way to look up with multiple keywords so that the resulting ominicomplete list is shorter to look up.

Thank you for the awesome plugin!

**Comment by jalvesaq** [comment]
I think it's better to let omni completion as is (completion from single keywords) and develop what you request for `:Zseek`. Currently, `:Zseek` uses only the first argument and ignores the rest. I don't have spare time for this now, but we may keep the issue open to remember me of doing this in the future.

The next step could be the integration of this new feature in something like [Telescope](https://github.com/nvim-telescope/telescope.nvim).

**Comment by jalvesaq** [comment]
I forgot to say, but you can use the `collection` option in the Markdown's YAML metadata to restrict the search to specific Zotero folders.

**Comment by jalvesaq** [comment]
@adam-coates implemented an integration with telescope.

@acorreya, could you try it? Does it work as you expect?
