### ISSUE TITLE
Ignore .bib file in Quarto Documents for Omnicomplete

### ISSUE THREAD

**Issue by wklimowicz** [jalvesaq/zotcite#47]
Hi,

Firstly just wanted to say a big thank you for this and especially for Nvim-R, I've used it basically every day for a few years.

I can't get the zotcite omnicomplete working properly in quarto documents,  while also having the bib file in the same directory to generate the bibliography: 

### Case 1: Omnicomplete working but bibliography breaks
If I just make a qmd document without the settings in YAML, omnicomplete works fine:
```qmd
---
title: Test
---
Omnicomlete from the Zotero database works here.
```
However to get the html output to display in quarto you need the extra snippet from the documentation:

### Case 2: Bibliography working but Omnicomplete breaks
 
```qmd
---
title: Test
bibliography: example_zotcite.bib
filters:
  - zotref.py
---
The YAML generates an `example_zotcite.bib` file in the same directory, 
and thereafter Omnicomplete only gets whatever is already in the `bib` file - 
you can't complete any extra references from Zotero.
```
I've either missed a setting in the documentation, or there needs to be a way for Zotcite to ignore the .bib file for completion in quarto documents.

I've tested this with a minimal .vimrc:

```vim
set nocompatible
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'jalvesaq/Nvim-R'
Plugin 'jalvesaq/zotcite'
call vundle#end() 
filetype plugin indent on 
```
Many thanks for all your work on these Plugins!

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue: even after the bib file is generated, the completion keeps getting items from Zotero. I tried with Neovim and vim-plug, and with Vim and your minimal vimrc (Vundle).

**Comment by wklimowicz** [comment]
So I've tried digging a bit more to identify the problem, since it always replicates for me.

![image](https://user-images.githubusercontent.com/62679873/177094234-39abd64e-ec0f-4b53-a6bb-8c62d2978d11.png)

By default my omnifunc is `CompleteR`, but if I manually run `set omnifunc=zotcite#CompleteBib` the quarto document works - (Zotero completion, bib file generation, etc), but code completion stops working. So the problem is the autocomplete from the bib file switches off the `zotcite#CompleteBib` element in `CompleteR`.

I can "fix" it by commenting out lines 187 - 200 in `ftplugin/rmd_nvimr.vim` in Nvim-R:

![image](https://user-images.githubusercontent.com/62679873/177097716-07359428-fcf5-4737-8c91-7cb0e4619173.png)

I'm not sure if that gives you any ideas on how to fix it permanently? I can obviously just keep this commented out, but I'm guessing other people might have the same. I'm running Fedora 36 and Neovim 0.8.

**Comment by jalvesaq** [comment]
I installed the `python3-pybtex` package, and now I can replicate the issue.

**Comment by wklimowicz** [comment]
It works now! Many thanks for the speedy fix, and all the work you do on these packages!
