### ISSUE TITLE
how to set up with nvim-cmp

### ISSUE THREAD

**Issue by thudjx** [jalvesaq/zotcite#49]
Sorry to misuse issue to ask questions, but I couldn't find anywhere else to ask for help.
I am a neovim user, and I am trying to set up a autocompletion for references from zotero database. I use [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) as the completion engine. To use this engine, a `source` keyword, functioning as some kind of interface, needs to be set. However, it seems that the keyword is not provided by `zotcite`.
I have installed `zotcite` but the auto completion didn't occur. So I am wondering if I need to set up for the `nvim-cmp` first? Or maybe I haven't set up `zotcite` correctly?

**Comment by jalvesaq** [comment]
I prefer to trigger the completion manually, but if you want to try automatic completion I believe you need an engine that you can configure to do omni completion after typing the `@` key plus at least two other letters. I don't know if `nvim-cmp` can be configured in such a way.

**Comment by thudjx** [comment]
Thanks! 
By the way, is there anyway to reset the trigger key to, say `<leader>xo`?

**Comment by jalvesaq** [comment]
I created a source for `nvim-cmp`. Please, try it: https://github.com/jalvesaq/cmp-zotcite
