### ISSUE TITLE
Citation style

### ISSUE THREAD

**Issue by gmoneymagna** [jalvesaq/zotcite#50]
Is there a way to change the citation style? For instance, I am trying to have my inline citations and bibliography in the American Medical Association style. Thank you.

**Comment by jalvesaq** [comment]
This is a general pandoc question, not specific to Zotcite. See, for example: https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html#changing-citation-style

As far as I remember, you can put tye `csl` file either in the current directory (where the document you are editing is) or in the `~/.pandoc` directory. In my `~/.pandoc` directory, I have a symbolic link to `abnt.csl` named `default.csl`.  That is, I don't need the `csl` field in the YAML header if I want to use the ABNT citation style.
