### ISSUE TITLE
vim-plug installs Zotcite but :Zinfo shows nothing

### ISSUE THREAD

**Issue by GeoffRussell** [jalvesaq/zotcite#52]
Hi,

I ran :PlugInstall and install looked good.

Opened an  xxx.md file

:Zinfo       nothing ... no error ... just nothing

@somekey <C_X><C_O>  gives a message "omnifunc is not set"

What am I missing?

Cheers,
Geoff Russell

**Comment by GeoffRussell** [comment]
Have got code running by setting zotcite_filetypes
But not finding my citations ...

[20 minutes later] 

And now it is ... curious ... I have a couple of thousand refs, maybe just taking time to build whatever 

No matter.  Seems to be working fine now! Many thanks.

**Comment by dld2517** [comment]
What plugin manager do you use for vim? I tried putting the file into my .vim/plugin folder and in .vim/ftplugin/ I tried the autoload/zotcite.vim and plugin/zotcite.vim (which has just zInfo function in it). I have not had any luck only errors.
