### ISSUE TITLE
manuel refreash zotcite reference.

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#6]
Hi Jalvesaq.

I have a issue, where it seems that zotcite don't update it's 'database'. I workflow:

foo.Rmd is open for writing.
Zotero is open. I then finds an reference(foobar2014, I want to use, so I import it to Zotero with ISBN.
Then in foo.Rmd I try to insert the reference with @foobar. Now zotcite don not seem to have found the newly created entrens in Zotero.

Can I trigged an update manuel?

Greetings from denmark

**Comment by olesendan** [comment]
Hi Jalvesaq.

I think I have found the issue. I see now, that there is no problems with the connection to Zotero.

It seems, that if there is not an author listet in Zotero, but instead an Editor for a book, then zotcite do not pick up the editor. 

Should I make a feature reqouest, for zotcite to pick editors and maybe contributors

Greetings from denmark

**Comment by jalvesaq** [comment]
On Thu, Jun 13, 2019 at 12:38:21PM -0700, Dan Olesen wrote:
> It seems, that if there is not an author listet in Zotero, but instead an Editor for a book, then zotcite do not pick up the editor. 
> 
> Should I make a feature reqouest, for zotcite to pick editors and maybe contributors

Yes, please.

**Comment by jalvesaq** [comment]
Could you, please, update the plugin and try again?

**Comment by olesendan** [comment]
Hi Jalvesaq.

So far, your commit seems to work.

Greetings from denmark

**Comment by olesendan** [comment]
Hi Again.

I was a bit to fast.

It seems now, that it only looks in the open document. It this cahnge possible with your commit, or have I done something, not that I recall that.

**Comment by jalvesaq** [comment]
I'm sorry, but I didn't understand what you mean by "it only looks in the open document".

**Comment by olesendan** [comment]
Hi Jalvesaq.

I've had a couple of times, where zotcite stops doing omnicomplete, or there only comes suggestions from the current file in the buffer.

It seems, that sometimes when I knitr via nvim-r, a bib file is created, which then stops zotcite. when I delete the bib file, zotcite starts working again.

Have you experienced this beahviour?

**Comment by jalvesaq** [comment]
I can't replicate the issue. Zotcite does not create a bib file, but it includes the `zotbib` script that might be used to generate a bib file. Are you running `zotbib` instead of using `zotref` as filter?

**Comment by olesendan** [comment]
Hi Jalvesaq.

Sorry for the late reply.

regarding the issue with authors, I will open a new issue. I'm closing this one, because you solved my question.

I will look in to, if I'm using zotref or zotbib, because I have no idea.
