### ISSUE TITLE
Znote and Zannotations returns no note and annotations

### ISSUE THREAD

**Issue by samtrek** [jalvesaq/zotcite#61]
The Znote and Zannotations returned no note and no annotations  despite I have made annotations on the pdf of the cited author, and even when the note for the annotations have also been extracted nothing was returned. I have checked with Zinfo and everything seems to be in order.

**Comment by jalvesaq** [comment]
Both are working here (Debian testing, Neovim 0.10.0-dev):

  - Annotations made with Evince and extracted by `zotcite/python3/pdfnotes.py`.
  - Annotations made in Zotero's pdf viewer and extracted with `:Zannotations`.

I can't fix the bug because I can't replicate it.

**Comment by samtrek** [comment]
I will have to close it, everything seems to be working again, something must have gone awry due to system update ( Arch linux lts with Neovim), thank you for the quick feedback.
