### ISSUE TITLE
Is there a way to change the conceallevel?

### ISSUE THREAD

**Issue by tdyoshida** [jalvesaq/zotcite#66]
Hi! I just started using this plugin, and so far I feel like this is what I've been looking for.
One problem I have is the conceallevel. It looks like the conceallevel is set to 2 by zotcite, which works fine for markdown.

However, it also changes my Rmarkdown file to hide the chunk delimiters (\`\`\`{r} and \`\`\`).
It still shows the chunk label, but the end of the chunk delimiter is completely hidden. 

For Rmarkdown, I'd prefer to set the conceallevel to 0.
I created rmd.lua (`vim.opt.conceallevel = 0`) in ~/.config/ftplugin or tried to setup autocmd, but looks like the zotcite's setting overrides them.
Now I set keymaps to change between conceallevels, which work okay, but not ideal. Is there a way to accomplish this automatically?

I appreciate your help!

**Comment by jalvesaq** [comment]
Chunk delimiters are not hidden here. Do you have any additional syntax plugin installed?

**Comment by tdyoshida** [comment]
Thanks for your quick response!

I do use nvim-treesitter, and pictures below show the difference by enabling/disabling treesitter and zotcite.

**zotcite: enabled; treesitter: enabled**
<img width="657" alt="with_zotcite_with_treesitter" src="https://github.com/jalvesaq/zotcite/assets/61808096/237d9d09-b099-4377-a61c-4aafed8e9fc9">

**zotcite: enabled; treesitter: disabled**
<img width="657" alt="with_zotcite_without_treesitter" src="https://github.com/jalvesaq/zotcite/assets/61808096/faac8ee7-1ade-4f96-b7f0-d432477d7ae0">

**zotcite: disabled; treesitter: enabled**
<img width="657" alt="without_zotcite_with_treesitter" src="https://github.com/jalvesaq/zotcite/assets/61808096/2dd476b1-41a2-431a-91ea-32000cb802ef">

**zotcite: enabled; treesitter: enabled; conceallevel=0**
<img width="657" alt="with_zotcite_with_treesitter_conceallevel0" src="https://github.com/jalvesaq/zotcite/assets/61808096/5f27ce3a-b88b-4de2-920b-8f1429d3ddeb">

You can see that (zotcite: disabled; treesitter: enabled) and (zotcite: enabled; treesitter: enabled; conceallevel=0) look the same, and this is what I'd like. Of course disabling zotcite is not an option, but I do want to keep treesitter too...

Sorry for bothering you for non-essential matter, but I appreciate your help!

**Comment by jalvesaq** [comment]
I guessed that you were using `vim-pandoc-syntax`. I didn't install it, but looking at its code, it seems that adding "inlinecode" to its conceal blacklist was necessary to avoid hiding backticks. Anyway, the option below should make zotcite set `conceallevel` as you want:

```vim
let zotcite_conceallevel = 0
```

**Comment by tdyoshida** [comment]
I'm sorry what I wrote in the previous post was incorrect.
Disabling `markdown` in treesitter does make the chunk delimiters to be visible.
Personally I prefer enabling `markdown` highlights, and I'll stick to use `zotcite_conceallevel` option for Rmd files.
Thanks!

**Comment by jalvesaq** [comment]
Now I'm understanding a bit more about how tree-sitter works. You may try to avoid the concealing of code block delimiters by creating the following file:

`~/.config/nvim/queries/markdown/highlights.scm`:

```
;; Undo conceal of language name
(fenced_code_block
  (info_string (language) @none
  (#set! noconceal)))
```
