### ISSUE TITLE
pop up box omnicomplete

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#7]
Hi Javlesaq.

when I'm writing, and the cursor is placed on the rigth side of the document. Then the popup box is posistioned outside the document, which results in, that I can not see the entries.

Have you seen this before?

Greetings from denmark

**Comment by jalvesaq** [comment]
This is a Vim/Neovim issue, not specific to zotcite. It happens with any kind of completion menu.
The issue doesn't annoy me because I usually have free space on the right.
