### ISSUE TITLE
Use @citekey to cite document

### ISSUE THREAD

**Issue by anandkumar89** [jalvesaq/zotcite#75]
I mostly use `@citekey` to cite references (in latex, markdown, obsidian). I am not sure how to achieve this using zotcite.

Since zotero database is being read, would it not be possible to use `@zoteroKey#citekey` from  `betterbibtex` to create a citation format just for the sake of maintaining uniformity across all notes. citekeys are available in `better-bibtex.sqlite` (table `citationkey`)

![Screenshot 2024-03-16 at 5 50 59 PM](https://github.com/jalvesaq/zotcite/assets/12571250/596caed0-1771-4b42-8db9-0a03a4cf5179)

---

**An alternative implementation using bib file**: (could ignore this section) Automatically exported and updated zotero .bib file could be used for autocompletion/citing _and_ using zotero database only when it is required to extract notes (stored in database). Benefit is ability to use zotcite for citations (just want to cite, but not extract notes) even when zotero is not available. When zotero is installed, bibfile _could_ allow faster processing (not sure).

setup from zotero side would require using `zotero + better_bibtex`.

**Implementation**: to recover notes all we need is `zoterokey` and `file_path`. `zoterokey` could be either retrieved from `file` in exported bib

<img width="1270" alt="Screenshot 2024-03-16 at 5 51 25 PM" src="https://github.com/jalvesaq/zotcite/assets/12571250/42b77b25-f242-4300-8479-0c56523000e0">

 for people who use `zotfile` or `linked file` -  `zoterokey` could be found from `citekey`  in `better-bibtex.sqlite` (table `citationkey`)

**Comment by jalvesaq** [comment]
> Since zotero database is being read, would it not be possible to use `@zoteroKey#citekey` from `betterbibtex` to create a citation format just for the sake of maintaining uniformity across all notes. citekeys are available in `better-bibtex.sqlite` (table `citationkey`)

The `#citekey` part is deleted before running the `citeproc` filter. It might be anything, and there would be no problem if it were a `betterbibtex` citation key, but I can't see any benefit of using `betterbibtex` to write something that will be deleted. You should get about the same result with:

```vim
let $ZCitationTemplate = '{Authors}{Year}
```

> Benefit is ability to use zotcite for citations (just want to cite, but not extract notes) even when zotero is not available. 

Please, see the documentation on `:Zrefs`. You can use it to include the references in the YAML header. Please, also search for "zotcite.bib" in the documentation. If you put `bibliography: "anyname_zotcite.bib"` in the YAML header, zotcite will update the bibfile.
