### ISSUE TITLE
Zotcite requires python3

### ISSUE THREAD

**Issue by realhackcraft** [jalvesaq/zotcite#78]
I get the error: `Zotcite requires python3` event when I have it.

`:echo g:python3_host_prog       > /usr/local/bin/python3`
`:echo g:loaded_python3_provider > 1`
`:checkhealth provider.python    >`

```

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- pyenv: Path: /opt/homebrew/Cellar/pyenv/2.4.1/libexec/pyenv
- pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
- WARNING pyenv: Root does not exist: /Users/Hackcraft_/.pyenv
  . Ignoring pyenv for all following checks.
- Using: g:python3_host_prog = "/usr/local/bin/python3"
- Executable: /usr/local/bin/python3
- Python version: 3.12.0
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV
```

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/zotcite/issues/53

**Comment by realhackcraft** [comment]
I do that (well, not exactly as the package is now call pynvim) and the issue still persists.

**Comment by realhackcraft** [comment]
> - OK Latest pynvim is installed.

**Comment by jalvesaq** [comment]
I'm sorry, but I can only say that it works here. I have this in my `init.lua`:

```lua
vim.g.python3_host_prog = '/home/aquino/.py3env/bin/python'
```

Maybe someone else reading this thread will be able to help you.

**Comment by realhackcraft** [comment]
I think I somehow fixed it. I have no idea what I did but it works now. I'm going to close this issue.
