### ISSUE TITLE
omnifocus not set in markdown

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#8]
Hi Jalvesaq.

I've just messed around with a markdown file foo.md

I get this error, when I try to insert a citation.

Error detected while processing function zotcite#Seek[1]..zotcite#getmach[2]..pr
ovider#python3#Call:                                                            
line   18:                                                                      
error caught in request handler 'python_eval ['ZotCite.GetMatch("peter", "/home/
dano/Desktop/test.md")']':                                                      
Traceback (most recent call last):                                              
  File "/usr/lib/python3/dist-packages/neovim/plugin/script_host.py", line 166, 
in python_eval                                                                  
    return eval(expr, self.module.__dict__)                                     
  File "<string>", line 1, in <module>                                          
  File "/home/dano/.config/nvim/bundle/zotcite/python3/zotero.py", line 491, in 
GetMatch                                                                        
    collections = self._d[d]                                                    
KeyError: '/home/dano/Desktop/test.md'                                          
Error detected while processing function zotcite#Seek[1]..zotcite#getmach: 

Greetings from denmark

**Comment by jalvesaq** [comment]
Whenever the file type is set for a buffer or the buffer is written, zotcite looks for the field "collection" in the YAML header. I wonder how you manage to get a markdown document that didn't have its collection field checked but whose omnifunc calls zotcite's omnicompletion. Did you set `omnifunc` in your vimrc?

Anyway, the issue should be fixed now.
