### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by raffaem** [jalvesaq/zotcite#84]
I moved my Zotero data folder in another path, and now I get the following error:

```
➜  pandoc_compile_article_pdf syllabus_EOA.md
Please, check if $ZoteroSQLpath is correct: "PATH/zotero" not found.
Traceback (most recent call last):
  File "PATH/zotcite/python3/zotref.py", line 117, in <module>
    r = z.GetYamlRefs(c)
        ^^^^^^^^^^^^^^^^
  File "PATH/zotcite/python3/zotero.py", line 681, in GetYamlRefs
    for e in self._e:
             ^^^^^^^
AttributeError: 'ZoteroEntries' object has no attribute '_e'
Error running filter PATH/zotcite/python3/zotref.py:
Filter returned error status 1
```

The error message should specify that `ZoteroSQLpath` must point to the "zotero.sqlite" file, not to the folder that contains the file (i.e., not to the data folder)

**Comment by jalvesaq** [comment]
Thank you for reporting the issue! It now will work with either a directory or file path on the master `branch`.

On the `vim` branch, I only improved the error message.
