### ISSUE TITLE
use other references when no author

### ISSUE THREAD

**Issue by olesendan** [jalvesaq/zotcite#9]
Hi.

I have a lot of references in zotero, which are not article, ex. programs, homepages, presentations, etc.

Many of these items, do not have an author, but istead ex. presenter, programmer, contributor etc.

It seems to me, that zotcite only looks at authors, and now one more from issue #6

Is it possible, for zotcite to lookup everything under creator in zotero regardless that it's not listed as author.

Greetings from denmark

**Comment by jalvesaq** [comment]
It should be fixed now. Could you try again, please?

**Comment by olesendan** [comment]
Hi Jalvesaq.

It seems to work, for the refs, listet in your commit to this issue.

But  there are other items, which it could be nice to reference in zotcite. 

ex. R project. 
in zotero, I have R-project as a computer program, and R Core Team as a contributor. Zotcite does not find this entry in zotero. But a computer program, can also have a creator, who is a programmer.

I think that across all items in zotero, there is alot of different creators.

Can you imagine, that zotcite is able to lookup all possible creators?

Greetings from Denmark

**Comment by jalvesaq** [comment]
Did you try completing by the title? For example `@project`.

**Comment by jalvesaq** [comment]
Note: the output of `citation()` includes the word "project" only in the "URL" field, and I opted for adding R as a book because I could easily find appropriate Zotero fields for all BibTeX. Instead of "Organization", I used the field "Publisher" for "R Foundation for Statistical Computing".

**Comment by jalvesaq** [comment]
I see the problem now. Here is a complete list of types of creators:
https://www.zotero.org/support/kb/item_types_and_fields#item_creators
And some of them (marked with asterisks) should not be cited, including contributors.

**Comment by olesendan** [comment]
Hi Jalvesaq.

I see now. From reading your link, my understanding is, that for a computer program, we can use programmer in citations,. Do you agree?

Greetings from denmark.

**Comment by jalvesaq** [comment]
Yes, "Programmer" is listed as a valid "creator". But depending on the citation style that you are using it might be necessary to adjust the data in Zotero. We may have to put a piece of information in the wrong field or classify the work as the wrong type to get the reference correctly formatted.

Wrong results may also be bugs in zotcite. If you type `<Leader>zy` in Normal mode over a citation key, you will see the Yaml output passed to `pandoc-citeproc`. Please, report any fields that are being wrongly translated from Zotero into Yaml.

**Comment by jalvesaq** [comment]
Could you update zotcite and try again, please? I added support for different types of creators.

You can type `<Local>za` over a citation key to see how its fields are stored in zotcite and `<Local>zy` to see how the reference is passed to `pandoc-citeproc`. Some conversions are required to make the reference to be correctly formatted by `pandoc-citeproc`. For example, "programmer" and "artist" are converted into "author", "seriesEditor" is converted into "collection-editor", and so on...

If a reference is not correctly formatted, the reasons might be:

- The citation style does not support this kind of reference.
- Zotcite did not translate the type of work correctly (see `_zct` in `python3/zotero.py`).
- Zotcite did not translate the Zotero field into CSL field correctly (see `_zcf` in `python3/zotero.py`).
- Zotcite did not recognize the field as a creator field (see `_creators`  in `python3/zotero.py`).
